### ISSUE TITLE
Warlock talent tree can't be exported

### ISSUE THREAD

**Issue by ghost** [NumyAddon/TalentTreeViewer#1]
I was unable to export a build from the addon to the UI for a warlock. I noticed that in the UI, Demonic Circle is already given for free (apparently for all specs which raises the question why it's in the talent tree at all) where in the addon it requires a point to be spent. I was able to make the same build on Wowhead and correctly import it in the UI.

**Comment by Numynum** [comment]
Hi, thanks for letting me know, should be fixed next update :)
(turns out I didn't take into account a situation where all specs would get a talent for free, as like you say.. it makes no sense :p)
