### ISSUE TITLE
Taint

### ISSUE THREAD

**Issue by rakkarage** [NumyAddon/TalentTreeViewer#3]
I think this causes a taint? I disable this and talent tree tweaks and everything is fine... enable them and get taint error...
https://gist.githubusercontent.com/rakkarage/45f7b12836f889c2c2e8a442fbfa2bd8/raw/e0222ae449720cfce5c739eb699aefb9a35c4069/taint.log
here is the log... at the bottom it seems to start with TelentViewer?

**Comment by Numynum** [comment]
hi, this should be fixed in next update :)
