### ISSUE TITLE
Need better position for option

### ISSUE THREAD

**Issue by EKE00372** [NumyAddon/TalentTreeViewer#5]
![image](https://github.com/NumyAddon/TalentTreeViewer/assets/1412472/bc9ada58-3754-48be-8607-17a8c9d60389)
for ppl using fonts much wide such like monospaced font will show like pic.
I think **Ignore Restrictions** can move to right side of abandon mark because it's empty.

btw, if you interested localization, i can support zhTW/zhCN for TalentLoadoutManager and TalentTreeTweaks.

**Comment by Numynum** [comment]
I'll look at shifting things around 👍 

I've never really looked into localization for addons tbh, I'll take a look at some of the option and let you know 👌

**Comment by Numynum** [comment]
I've moved the checkbox to the right like you suggested, available in the latest release

Localization is now enabled for [TalentTreeViewer](https://legacy.curseforge.com/wow/addons/talenttree-viewer/localization) and [TalentTreeTweaks](https://legacy.curseforge.com/wow/addons/talent-tree-tweaks/localization), feel free to add any translations you can 🙂
(other addons, like TalentLoadoutManager, will be supported later)

**Comment by EKE00372** [comment]
will do translate next week

**Comment by Numynum** [comment]
take your time, any translation you add, should automatically be included on the next release(s) 🙂

**Comment by EKE00372** [comment]
Talent Tree Viewer done.
curse have 9 but i only saw 6 translations in the actual file, and **Select another Specialization** handle in XML so cannot translate it.

**Comment by EKE00372** [comment]
Talent Tree Viewer finished

PS. suggest remove IDs in translate, probably they dont need translate instead SpellIDs......?
