### ISSUE TITLE
Curse package still has buggy LibUIDropDownMenu

### ISSUE THREAD

**Issue by justinkb** [NumyAddon/TalentTreeViewer#6]
Seems you never repackaged it for your "- Changed all globals to use L_NUMY_ or L_Numy as prefixes, instead of L_ for compatibility with the original lib" fix

As is, it causes interference issues

**Comment by Numynum** [comment]
ah, good catch, updated all addons that use the forked lib now, thanks 🙂

**Comment by justinkb** [comment]
Great addon, by the way.

Not on my PC now, so can't easily create a new issue, but I noticed when
browsing the talents for another class, some talents might show versions of
a talent that belongs to another spec for that class. For example, if I am
on my DH viewing the trees for Destruction Warlock, it'll show the
descriptions of the Affliction version of Sargerite Ingenuity (I think
that's what the talent is called)

**Comment by justinkb** [comment]
Sargerei Technique, sorry (as well as Socrethar's Guile next to it)

**Comment by Numynum** [comment]
this sometimes happens when multiple specs have the same spell, it's not possible to show the spec specific tooltip (same would happen if you link the spell in chat, and check the tooltip from that)
